Abundance_Nk.Web/Areas/Admin/ViewModels/AdmissionProcessingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using Abundance_Nk.Business;
using Abundance_Nk.Model.Model;
using System.Web.Mvc;
using Abundance_Nk.Web.Models;

namespace Abundance_Nk.Web.Areas.Admin.ViewModels
{
    public class AdmissionProcessingViewModel
    {
        private ApplicationFormLogic applicationFormLogic;

        public AdmissionProcessingViewModel()
        {

            Session = new Session();
            applicationFormLogic = new ApplicationFormLogic();
            ApplicationForms = new List<ApplicationForm>();

            SessionSelectList = Utility.PopulateSessionSelectListItem();
        }

        public Session Session { get; set; }
        public List<ApplicationForm> ApplicationForms { get; set; }
        public List<SelectListItem> SessionSelectList { get; set; }

        public List<ApplicationForm> GetApplicationsBy(bool rejected, Session session)
        {
            try
            {
                ApplicationForms = applicationFormLogic.GetModelsBy(af => af.Rejected == rejected && af.APPLICATION_FORM_SETTING.Session_Id == session.Id);
                return ApplicationForms;
            }
            catch (Exception)
            {
                throw;
            }
        }

        



    }




}

Abundance_Nk.Web/Areas/Admin/Controllers/AdmissionProcessingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using Abundance_Nk.Model.Entity;
using Abundance_Nk.Business;
using Abundance_Nk.Model.Model;
using Abundance_Nk.Web.Areas.Admin.ViewModels;
using Abundance_Nk.Web.Controllers;

namespace Abundance_Nk.Web.Areas.Admin.Controllers
{
    public class AdmissionProcessingController : BaseController
    {
        private AdmissionProcessingViewModel viewModel;
        private Abundance_Nk_NekedeEntities db = new Abundance_Nk_NekedeEntities();

        public AdmissionProcessingController()
        {
            viewModel = new AdmissionProcessingViewModel();
        }

        public ActionResult Index()
        {
            ViewBag.SessionId = viewModel.SessionSelectList;
            
            return View(viewModel);
        }
        [AllowAnonymous]
        public ActionResult Index2()
        {
            try
            {
                string inv = "FPN150000022551";
                PaymentLogic pl = new PaymentLogic();
                Payment payment = pl.GetBy(inv);

                //AppliedCourseLogic appliedCourseLogic = new AppliedCourseLogic();
                //AppliedCourse appliedCourse = appliedCourseLogic.GetModelBy(a => a.Person_Id == 32);

                //AdmissionCriteriaLogic admissionCriteriaLogic = new AdmissionCriteriaLogic();
                //ViewBag.RejectReason = admissionCriteriaLogic.EvaluateApplication(appliedCourse);

                
            }
            catch (Exception ex)
            {
                ViewBag.RejectReason = ex.Message + " --- " + ex.StackTrace;
                SetMessage("Operation failed! " + ex.Message, Message.Category.Error);
            }

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult AcceptOrReject(List<int> ids, int sessionId, bool isRejected)
        {
            try
            {
                if (ids != null && ids.Count > 0)
                {
                    List<ApplicationForm> applications = new List<ApplicationForm>();

                    foreach (int id in ids)
                    {
                        ApplicationForm application = new ApplicationForm() { Id = id };
                        applications.Add(application);
                    }

                    ApplicationFormLogic applicationFormLogic = new ApplicationFormLogic();
                    bool accepted = applicationFormLogic.AcceptOrReject(applications, isRejected);
                    if (accepted)
                    {
                        Session session = new Session() { Id = sessionId };
                        viewModel.GetApplicationsBy(!isRejected, session);
                        SetMessage("Select Applications has be successfully Accepted.", Message.Category.Information);
                    }
                    else
                    {
                        SetMessage("Opeartion failed during selected Application Acceptance! Please try again.", Message.Category.Information);
                    }
                }
            }
            catch (Exception ex)
            {
                SetMessage("Operation failed! " + ex.Message, Message.Category.Error);
            }

            return PartialView("_ApplicationFormsGrid", viewModel.ApplicationForms);
        }

        [HttpPost]
        public ActionResult FindBy(int sessionId, bool isRejected)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Session session = new Session() { Id = sessionId };
                    viewModel.GetApplicationsBy(isRejected, session);
                }

            }
            catch (Exception ex)
            {
                TempData["msg"] = "Operation failed! " + ex.Message;
            }

            return PartialView("_ApplicationFormsGrid", viewModel.ApplicationForms);
        }

        //public ActionResult FindAllAcceptedBy(int sessionId)
        //{
        //    try
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            Session session = new Session() { Id = sessionId };
        //            viewModel.GetApplicationsBy(false, session);
        //        }
        //    }
        //    catch (Exception ex)
        //    {

        //    }

        //    return PartialView("_ApplicationFormsGrid", viewModel.ApplicationForms);
        //}

        //[HttpPost]
        //public void ApproveOrReject(List<int> ids, string status)
        //{
        //    try
        //    {
        //        TempData["msg"] = "Operation was successful.";
        //    }
        //    catch(Exception ex)
        //    {
        //        TempData["msg"] = "Operation failed! " + ex.Message;
        //    }
        //}
       
        

        //[HttpPost]
        //public ActionResult Index(AdmissionProcessingViewModel admissionProcessingViewModel)
        //{
        //    //bool rejected = admissionProcessingViewModel.Rejected;
        //    //admissionProcessingViewModel.GetApplicationsBy(admissionProcessingViewModel.Rejected);

        //    return View(admissionProcessingViewModel.ApplicationForms);
        //}

        // GET: /Admin/AdmissionProcessing/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            APPLICATION_FORM application_form = db.APPLICATION_FORM.Find(id);
            if (application_form == null)
            {
                return HttpNotFound();
            }
            return View(application_form);
        }

        // GET: /Admin/AdmissionProcessing/Create
        public ActionResult Create()
        {
            ViewBag.Application_Form_Setting_Id = new SelectList(db.APPLICATION_FORM_SETTING, "Application_Form_Setting_Id", "Exam_Venue");
            ViewBag.Application_Programme_Fee_Id = new SelectList(db.APPLICATION_PROGRAMME_FEE, "Application_Programme_Fee_Id", "Application_Programme_Fee_Id");
            ViewBag.Payment_Id = new SelectList(db.PAYMENT, "Payment_Id", "Invoice_Number");
            ViewBag.Person_Id = new SelectList(db.PERSON, "Person_Id", "First_Name");
            return View();
        }

        // POST: /Admin/AdmissionProcessing/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Application_Form_Id,Serial_Number,Application_Form_Number,Application_Form_Setting_Id,Application_Programme_Fee_Id,Payment_Id,Person_Id,Date_Submitted,Release,Rejected,Reject_Reason,Remarks")] APPLICATION_FORM application_form)
        {
            if (ModelState.IsValid)
            {
                db.APPLICATION_FORM.Add(application_form);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Application_Form_Setting_Id = new SelectList(db.APPLICATION_FORM_SETTING, "Application_Form_Setting_Id", "Exam_Venue", application_form.Application_Form_Setting_Id);
            ViewBag.Application_Programme_Fee_Id = new SelectList(db.APPLICATION_PROGRAMME_FEE, "Application_Programme_Fee_Id", "Application_Programme_Fee_Id", application_form.Application_Programme_Fee_Id);
            ViewBag.Payment_Id = new SelectList(db.PAYMENT, "Payment_Id", "Invoice_Number", application_form.Payment_Id);
            ViewBag.Person_Id = new SelectList(db.PERSON, "Person_Id", "First_Name", application_form.Person_Id);
            return View(application_form);
        }

        // GET: /Admin/AdmissionProcessing/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            APPLICATION_FORM application_form = db.APPLICATION_FORM.Find(id);
            if (application_form == null)
            {
                return HttpNotFound();
            }
            ViewBag.Application_Form_Setting_Id = new SelectList(db.APPLICATION_FORM_SETTING, "Application_Form_Setting_Id", "Exam_Venue", application_form.Application_Form_Setting_Id);
            ViewBag.Application_Programme_Fee_Id = new SelectList(db.APPLICATION_PROGRAMME_FEE, "Application_Programme_Fee_Id", "Application_Programme_Fee_Id", application_form.Application_Programme_Fee_Id);
            ViewBag.Payment_Id = new SelectList(db.PAYMENT, "Payment_Id", "Invoice_Number", application_form.Payment_Id);
            ViewBag.Person_Id = new SelectList(db.PERSON, "Person_Id", "First_Name", application_form.Person_Id);
            return View(application_form);
        }

        // POST: /Admin/AdmissionProcessing/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Application_Form_Id,Serial_Number,Application_Form_Number,Application_Form_Setting_Id,Application_Programme_Fee_Id,Payment_Id,Person_Id,Date_Submitted,Release,Rejected,Reject_Reason,Remarks")] APPLICATION_FORM application_form)
        {
            if (ModelState.IsValid)
            {
                db.Entry(application_form).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");

Abundance_Nk.Web/Areas/Admin/Views/AdmissionProcessing/Create.cshtml
@model Abundance_Nk.Model.Entity.APPLICATION_FORM

@{
    //Layout = null;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>APPLICATION_FORM</h4>
            <hr />
            @Html.ValidationSummary(true)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Serial_Number, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Serial_Number)
                    @Html.ValidationMessageFor(model => model.Serial_Number)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Application_Form_Number, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Application_Form_Number)
                    @Html.ValidationMessageFor(model => model.Application_Form_Number)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Application_Form_Setting_Id, "Application_Form_Setting_Id", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Application_Form_Setting_Id", String.Empty)
                    @Html.ValidationMessageFor(model => model.Application_Form_Setting_Id)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Application_Programme_Fee_Id, "Application_Programme_Fee_Id", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Application_Programme_Fee_Id", String.Empty)
                    @Html.ValidationMessageFor(model => model.Application_Programme_Fee_Id)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Payment_Id, "Payment_Id", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Payment_Id", String.Empty)
                    @Html.ValidationMessageFor(model => model.Payment_Id)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Person_Id, "Person_Id", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Person_Id", String.Empty)
                    @Html.ValidationMessageFor(model => model.Person_Id)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Date_Submitted, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date_Submitted)
                    @Html.ValidationMessageFor(model => model.Date_Submitted)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Release, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Release)
                    @Html.ValidationMessageFor(model => model.Release)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Rejected, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Rejected)
                    @Html.ValidationMessageFor(model => model.Rejected)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Reject_Reason, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Reject_Reason)
                    @Html.ValidationMessageFor(model => model.Reject_Reason)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Remarks, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Remarks)
                    @Html.ValidationMessageFor(model => model.Remarks)
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Abundance_Nk.Web/Areas/Admin/Views/AdmissionProcessing/Index.cshtml
@model Abundance_Nk.Web.Areas.Admin.ViewModels.AdmissionProcessingViewModel

@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/responsive-tabs.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#buttons").hide();
                       
            BindSelectAll();
            BindSelectOne();

            $('#btnAccept').prop('disabled', true);
            $('#btnReject').prop('disabled', true);
            
            $("#btnAccept").click(function () {
                checkedIds = $(".ckb").filter(":checked").map(function () {
                    return this.id;
                });

                var rejected = false;
                var selectedSession = $("#Session_Id").val();
                if (selectedSession == "" || undefined) {
                    alert("No Session selected! Please select Session.");
                    return;
                }

                $.ajax({
                    type: "POST",
                    url: "@Url.Action("AcceptOrReject", "AdmissionProcessing")",
                    traditional: true,
                    data: { ids: checkedIds.toArray(), sessionId: selectedSession, isRejected: rejected },
                    beforeSend: function () {
                        $("#processing").show();
                    },
                    complete: function() {
                        $("#processing").hide();
                    },
                    success: SuccessFunc,
                    error: ErrorFunc,
                })

                function SuccessFunc(data, status) {
                    $("#data").html(data);
                    BindSelectAll();
                    BindSelectOne();
                }

                function ErrorFunc() {
                    alert("Operation failed!");
                }
            });
            
            $("#btnReject").click(function () {
                checkedIds = $(".ckb").filter(":checked").map(function () {
                    return this.id;
                });

                var rejected = true;
                var selectedSession = $("#Session_Id").val();
                if (selectedSession == "" || undefined) {
                    alert("No Session selected! Please select Session.");
                    return;
                }

                $.ajax({
                    type: "POST",
                    url: "@Url.Action("AcceptOrReject", "AdmissionProcessing")",
                    traditional: true,
                data: { ids: checkedIds.toArray(), sessionId: selectedSession, isRejected: rejected },
                beforeSend: function () {
                    $("#processing").show();
                },
                complete: function() {
                    $("#processing").hide();
                },
                success: SuccessFunc,
                error: ErrorFunc,
                })

            function SuccessFunc(data, status) {
                $("#data").html(data);
                BindSelectAll();
                BindSelectOne();
            }

            function ErrorFunc() {
                alert("Operation failed!");
            }
        });
            
            $("#find").click(function () {
                if ($("#rdYesRadio").is(':checked')) {
                    rejected = true;
                }
                else {
                    rejected = false;
                }
                
                var session = $("#Session_Id").val();
                if (session == "" || undefined){
                    alert("No Session selected! Please select Session.");
                    return;
                }

                $.ajax({
                    type: "POST",
                    url: "@Url.Action("FindBy", "AdmissionProcessing")",
                    traditional: true,
                    data: { sessionId: session, isRejected: rejected },
                    beforeSend: function () {
                        $("#loading").show();
                    },
                    complete: function () {
                        $("#loading").hide();
                    },
                success: SuccessFunc,
                error: ErrorFunc,
                });

            function SuccessFunc(data) {
                $("#data").html(data);
                $("#buttons").show();
                BindSelectAll();
                BindSelectOne();
            }

            function ErrorFunc() {
                alert("Operation failed!");
            }
            });

            function BindSelectAll() {
                if ($("#rdYesRadio").is(':checked')) {
                    rejected = true;
                }
                else {
                    rejected = false;
                }

                $("#selectAll").click(function (event) {
                    if (this.checked) {
                        $(".ckb").each(function () {
                            this.checked = true;

                            if (rejected) {
                                $('#btnAccept').prop('disabled', false);
                                $('#btnReject').prop('disabled', true);
                            }
                            else {
                                $('#btnReject').prop('disabled', false);
                                $('#btnAccept').prop('disabled', true);
                            }

                        });
                    }
                    else {
                        $(".ckb").each(function () {
                            this.checked = false;
                            $('#btnAccept').prop('disabled', true);
                            $('#btnReject').prop('disabled', true);
                        });
                    }
                });
            }

            function BindSelectOne() {
                if ($("#rdYesRadio").is(':checked')) {
                    rejected = true;
                }
                else {
                    rejected = false;
                }

                $(".ckb").click(function (event) {
                    
                    if (!this.checked) {
                        $('#selectAll').removeAttr('checked');
                        var count = $("[type='checkbox']:checked").length;

                        if (count > 0) {
                            if (rejected) {
                                $('#btnAccept').prop('disabled', false);
                                $('#btnReject').prop('disabled', true);
                            }
                            else {
                                $('#btnReject').prop('disabled', false);
                                $('#btnAccept').prop('disabled', true);
                            }
                        }
                        else {
                            $('#btnAccept').prop('disabled', true);
                            $('#btnReject').prop('disabled', true);
                        }
                    }
                    else {
                        //$('#btnAccept').prop('disabled', false);
                        if (rejected) {
                            $('#btnAccept').prop('disabled', false);
                            $('#btnReject').prop('disabled', true);
                        }
                        else {
                            $('#btnReject').prop('disabled', false);
                            $('#btnAccept').prop('disabled', true);
                        }
                    }
                });
            }
        });
        
        (function ($) {
            fakewaffle.responsiveTabs(['xs', 'sm']);
        })(jQuery);

        $('#myTab a').click(function (e) {
            e.preventDefault();
            $(this).tab('show');
        });

        function resizeIframe(obj) {
            obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
        }


    </script>
    }

    <h3 style="color:black">
       Admission Processing
    </h3>

  
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    
    <ul class="nav nav-tabs responsive" id="myTab">
        <li class="test-class active"><a class="deco-none misc-class" href="#how-to" data-toggle="tab">@*<span class="glyphicon glyphicon-cog"></span>*@ Accept / Reject Application</a></li>
        <li><a class="deco-none" href="#source" data-toggle="tab">Clear Applicant</a></li>
    </ul>

    <div class="tab-content responsive">
        <div class="tab-pane active" id="how-to">
           <br />
            @*<div class="panel panel-danger-head">*@
                @*<div class="panel-heading">*@
                    <div class="alert alert-dismissible alert-danger">
                        <h3>This interface enables users to view, Accept or Reject Application.</h3>
                        <p><b>Users can Accept or Reject Application Form by simple selecting an Academic Session, Accepted or Rejected from the drop dowm and options respectively. Then click the Find button to search. The search result is displayed in a tabular format below. Users can Accept an Application by selecting the appropriate application and click the Accept button below.</b></p>
                    </div>
            @*</div>*@
             

                <div class="panel panel-default">

                    <div class="panel-body ">
                        <div class="form-inline ">
                            <div class="form-group">
                                <span style="font-size:11pt">Academic Session</span>
                            </div>

                            <div class="form-group">
                                @Html.DropDownListFor(m => m.Session.Id, (IEnumerable<SelectListItem>)ViewBag.SessionId, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Session.Id)
                            </div>

                            <div class="form-group">
                                <div class="rdio rdio-default">
                                    @Html.RadioButton("Rejected", false, new { id = "rdNoRadio" })
                                    <label for="rdNoRadio">Accepted</label>
                                </div>

                            </div>

                            <div class="form-group">
                                <div class="rdio rdio-default">
                                    @Html.RadioButton("Rejected", true, new { id = "rdYesRadio", @checked = "checked" })
                                    <label for="rdYesRadio">Rejected</label>
                                </div>

                            </div>

                            <div class="form-group">
                                <button class="btn btn-default btn-metro mr5" type="button" name="find" id="find" value="Find">Find</button>
                            </div>

                            <div class="form-group">
                                <div id="loading" style="display:none">
                                    <img src="@Url.Content("~/Content/Images/bx_loader.gif")" />
                                    <span>Loading ...</span>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

                <div id="data">
                    @Html.Partial("_ApplicationFormsGrid", Model.ApplicationForms)
                </div>
                <br />

                <div id="buttons">
                    <div class="form-inline ">
                        <div class="form-group">
                            <input type="button" id="btnAccept" value="Accept" class="btn btn-white btn-lg" />
                            <input type="button" id="btnReject" value="Reject" class="btn btn-white btn-lg" />
                        </div>

                        <div class="form-group">
                            <div id="processing" style="display:none">
                                <img src="@Url.Content("~/Content/Images/bx_loader.gif")" />
                                <span>Processing ...</span>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
    
        <div class="tab-pane" id="source">
            <div class="tab-pane active" id="how-to">
                <br />
               

            </div>

        </div>
    </div>
}

    <br />

Abundance_Nk.Web/Areas/Admin/Views/AdmissionProcessing/_ApplicationFormsGrid.cshtml
@model IEnumerable<Abundance_Nk.Model.Model.ApplicationForm>

@if (Model != null && Model.Count() > 0)
{
    <div class="table-responsive " style="color:black">
        <table class="table table-condensed grid-table table-head-alt mb30">
            <thead>
                <tr class="well" style="height:35px; vertical-align:middle">
                    <th>
                        @Html.CheckBox("selectAll")
                    </th>

                    <th>
                        Form Number
                    </th>
                    <th>
                        Name
                    </th>

                    <th>
                        Reject Reason
                    </th>
                </tr>
            </thead>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.CheckBox(" ", false, new { @class = "ckb", id = item.Id })
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Number)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Person.FullName)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.RejectReason)
                    </td>
                </tr>
            }
        </table>

    </div>
}