Abundance_Nk.Web/Areas/Admin/ViewModels/HostelViewModel.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Abundance_Nk.Model.Model;
using Abundance_Nk.Web.Models;

namespace Abundance_Nk.Web.Areas.Admin.ViewModels
{
    public class HostelViewModel
    {
        public HostelViewModel()
        {
            SessionSelectListItem = Utility.PopulateSessionSelectListItem();
            ProgrammeSelectListItem = Utility.PopulateAllProgrammeSelectListItem();
            //DepartmentSelectListItem = Utility.PopulateDepartmentSelectListItem(Programme);
            //HostelSeriesSelectListItem = Utility.PopulateHostelSeries();
            HostelSelectListItem = Utility.PopulateHostels();
            LevelSelectListItem = Utility.PopulateLevelSelectListItem();
        }

        public HostelRoom HostelRoom { get; set; }
        public HostelAllocationCriteria HostelAllocationCriteria { get; set; }
        public Hostel Hostel { get; set; }
        public HostelRoomCorner HostelRoomCorner { get; set; }
        public HostelSeries HostelSeries { get; set; }
        public List<HostelSeries> HostelSeriesList { get; set; }
        public List<HostelRoom> HostelRoomList { get; set; }
        public List<RoomSetting> RoomSettings { get; set; }
        public HostelType HostelType { get; set; }
        public List<HostelType> HostelTypes { get; set; }
        public string[] SelectedCorners { get; set; }
        public List<string> Corners { get; set; }
        public List<SelectListItem> DepartmentSelectListItem { get; set; }
        public List<SelectListItem> DepartmentOpionSelectListItem { get; set; }
        public List<SelectListItem> ProgrammeSelectListItem { get; set; }
        public List<SelectListItem> LevelSelectListItem { get; set; }
        public List<SelectListItem> SessionSelectListItem { get; set; }
        public List<SelectListItem> HostelSelectListItem { get; set; }
        public List<SelectListItem> HostelSeriesSelectListItem { get; set; }
        public List<SelectListItem> HostelRoomsSelectListItem { get; set; }

        public HostelAllocation HostelAllocation { get; set; }
        public HostelRequest HostelRequest { get; set; }
        public HostelAllocationCount HostelAllocationCount { get; set; }
        public List<HostelAllocationCount> HostelAllocationCounts { get; set; }
        public List<HostelAllocation> HostelAllocations { get; set; }
        public List<HostelRoomCorner> HostelRoomCorners { get; set; }
        public List<HostelRequest> HostelRequests { get; set; }
        public List<DistinctAllocation> DistinctAllocation { get; set; }

        public Session Session { get; set; }
        public Programme Programme { get; set; }
        public Level Level { get; set; }
        public Department Department { get; set; }

        public List<HostelAllocationCriteria> HostelAllocationCriterias { get; set; }
        public Model.Model.Student Student { get; set; }
        public Person Person { get; set; }
        public StudentLevel StudentLevel { get; set; }
    }
    public class DistinctAllocation
    {
        public string Level { get; set; }
        public string HostelType { get; set; }
        public string Hostel { get; set; }
        public string Series { get; set; }
        public long FreeAllocationCount { get; set; }
        public long ReservedAllocationAccount { get; set; }
        public long CriteriaCount { get; set; }
        public string RoomCorner { get; set; }
        public int UsedCriteriaCount { get; set; }
        public int UnusedCriteriaCount { get; set; }
    }
}

Abundance_Nk.Web/Areas/Student/ViewModels/HostelViewModel.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Abundance_Nk.Model.Model;
using Abundance_Nk.Web.Models;

namespace Abundance_Nk.Web.Areas.Student.ViewModels
{
    public class HostelViewModel
    {
        public HostelViewModel()
        {
            FeeTypeSelectListItem = Utility.PopulateFeeTypeSelectListItem();
        }

        public string ConfirmationOrder { get; set; }
        public Model.Model.Student Student { get; set; }
        public StudentLevel StudentLevel { get; set; }
        public Person Person { get; set; }
        public FeeType FeeType { get; set; }
        public Payment Payment { get; set; }
        public Session Session { get; set; }
        public HostelAllocation HostelAllocation { get; set; }
        public List<SelectListItem> FeeTypeSelectListItem { get; set; }
        public HostelFee HostelFee { get; set; }
    }
}

Abundance_Nk.Web/Areas/Admin/Controllers/HostelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Abundance_Nk.Business;
using Abundance_Nk.Model.Entity;
using Abundance_Nk.Model.Model;
using Abundance_Nk.Web.Areas.Admin.ViewModels;
using Abundance_Nk.Web.Controllers;

namespace Abundance_Nk.Web.Areas.Admin.Controllers
{
    public class HostelController : BaseController
    {
        private Abundance_Nk_NekedeEntities db = new Abundance_Nk_NekedeEntities();
        private HostelViewModel viewModel = null;

        // GET: Admin/Hostel
        public ActionResult Index()
        {
            var hOSTEL = db.HOSTEL.Include(h => h.HOSTEL_TYPE);
            return View(hOSTEL.ToList());
        }

        // GET: Admin/Hostel/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HOSTEL hOSTEL = db.HOSTEL.Find(id);
            if (hOSTEL == null)
            {
                return HttpNotFound();
            }
            return View(hOSTEL);
        }

        // GET: Admin/Hostel/Create
        public ActionResult Create()
        {
            ViewBag.Hostel_Type_Id = new SelectList(db.HOSTEL_TYPE, "Hostel_Type_Id", "Hostel_Type_Name");
            return View();
        }

        // POST: Admin/Hostel/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Hostel_Id,Hostel_Type_Id,Hostel_Name,Capacity,Description,Date_Entered,Activated")] HOSTEL hOSTEL)
        {
            if (ModelState.IsValid)
            {
                db.HOSTEL.Add(hOSTEL);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Hostel_Type_Id = new SelectList(db.HOSTEL_TYPE, "Hostel_Type_Id", "Hostel_Type_Name", hOSTEL.Hostel_Type_Id);
            return View(hOSTEL);
        }

        // GET: Admin/Hostel/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HOSTEL hOSTEL = db.HOSTEL.Find(id);
            if (hOSTEL == null)
            {
                return HttpNotFound();
            }
            ViewBag.Hostel_Type_Id = new SelectList(db.HOSTEL_TYPE, "Hostel_Type_Id", "Hostel_Type_Name", hOSTEL.Hostel_Type_Id);
            return View(hOSTEL);
        }

        // POST: Admin/Hostel/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Hostel_Id,Hostel_Type_Id,Hostel_Name,Capacity,Description,Date_Entered,Activated")] HOSTEL hOSTEL)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hOSTEL).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Hostel_Type_Id = new SelectList(db.HOSTEL_TYPE, "Hostel_Type_Id", "Hostel_Type_Name", hOSTEL.Hostel_Type_Id);
            return View(hOSTEL);
        }

        // GET: Admin/Hostel/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HOSTEL hOSTEL = db.HOSTEL.Find(id);
            if (hOSTEL == null)
            {
                return HttpNotFound();
            }
            return View(hOSTEL);
        }

        // POST: Admin/Hostel/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HOSTEL hOSTEL = db.HOSTEL.Find(id);
            db.HOSTEL.Remove(hOSTEL);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult ViewHostelTypes()
        {
            try
            {
                viewModel = new HostelViewModel();
                HostelTypeLogic hostelTypeLogic = new HostelTypeLogic();

                viewModel.HostelTypes = hostelTypeLogic.GetAll();
            }
            catch (Exception ex)
            {
                SetMessage("Error! " + ex.Message, Message.Category.Error);
            }

            return View(viewModel);
        }

        public ActionResult HostelTypeDetails(int id)
        {
            try
            {
                if (id > 0)
                {
                    viewModel = new HostelViewModel();
                    HostelTypeLogic hostelTypeLogic = new HostelTypeLogic();
                    HostelType hostelType = hostelTypeLogic.GetModelBy(h => h.Hostel_Type_Id == id);

                    viewModel.HostelType = hostelType;
                }
            }
            catch (Exception ex)
            {
                SetMessage("Error! " + ex.Message, Message.Category.Error);
            }
            return View(viewModel);
        }

        public ActionResult CreateHostelType()
        {
            HostelViewModel viewModel = new HostelViewModel();

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult CreateHostelType(HostelViewModel viewModel)
        {
            try
            {
                if (viewModel != null)
                {
                    HostelTypeLogic hostelTypeLogic = new HostelTypeLogic();
                    hostelTypeLogic.Create(viewModel.HostelType);

                    return RedirectToAction("ViewHostelTypes");
                }
            }
            catch (Exception ex)
            {
                SetMessage("Error! " + ex.Message, Message.Category.Error);
            }

            return View(viewModel);
        }

        public ActionResult EditHostelType(int id)
        {
            viewModel = new HostelViewModel();
            try
            {
                if (id == null || id <= 0)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                HostelTypeLogic hostelTypeLogic = new HostelTypeLogic();
                HostelType hostelType = hostelTypeLogic.GetModelBy(h => h.Hostel_Type_Id == id);
                if (hostelType == null)
                {
                    return HttpNotFound();
                }

                viewModel.HostelType = hostelType;
            }
            catch (Exception ex)
            {
                SetMessage("Error! " + ex.Message, Message.Category.Error);
            }

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditHostelType(HostelViewModel viewModel)
        {
            try
            {
                if (viewModel != null)
                {
                    HostelTypeLogic hostelTypeLogic = new HostelTypeLogic();
                    hostelTypeLogic.Modify(viewModel.HostelType);

                    SetMessage("Operation Successful!", Message.Category.Information);
                    return RedirectToAction("ViewHostelTypes");
                }
            }
            catch (Exception ex)
            {
                SetMessage("Error! " + ex.Message, Message.Category.Error);
            }

            return View(viewModel);
        }

        public ActionResult DeleteHostelType(int id)
        {
            try
            {
                if (id == null || id <= 0)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                viewModel = new HostelViewModel();
                HostelTypeLogic hostelTypeLogic = new HostelTypeLogic();
                viewModel.HostelType = hostelTypeLogic.GetModelBy(h => h.Hostel_Type_Id == id);

                if (viewModel.HostelType == null)
                {
                    return HttpNotFound();
                }
            }
            catch (Exception ex)
            {
                SetMessage("Error! " + ex.Message, Message.Category.Error);
            }


            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteHostelType(HostelViewModel viewModel)
        {
            try
            {
                HostelTypeLogic hostelTypeLogic = new HostelTypeLogic();
                hostelTypeLogic.Delete(h => h.Hostel_Type_Id == viewModel.HostelType.Hostel_Type_Id);

                SetMessage("Operation Successful!", Message.Category.Information);
                return RedirectToAction("ViewHostelTypes");
            }
            catch (Exception ex)
            {
                SetMessage("Error! " + ex.Message, Message.Category.Error);
            }

            return View(viewModel);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Abundance_Nk.Web/Areas/Admin/Views/Hostel/Create.cshtml
@model Abundance_Nk.Model.Entity.HOSTEL

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="col-md-1"></div>
    <div class="col-md-10">

        <div>
            @if (TempData["Message"] != null)
            {
                @Html.Partial("_Message", (Abundance_Nk.Model.Model.Message)TempData["Message"])
            }
        </div>

        <div class="panel panel-default">
            <div class="panel-heading panel-dark-head">
                <h4>Add Hostel</h4>
            </div>
            <div class="panel-body">
                <div class="col-md-12">

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                              
                            @Html.ValidationSummary(true)
                            <div class="form-group">
                                @Html.LabelFor(model => model.Hostel_Type_Id, "Hostel Type", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("Hostel_Type_Id", String.Empty)
                                    @Html.ValidationMessageFor(model => model.Hostel_Type_Id)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Hostel_Name, "Hostel Name", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Hostel_Name)
                                    @Html.ValidationMessageFor(model => model.Hostel_Name)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Capacity, "Number Of Rooms", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Capacity)
                                    @Html.ValidationMessageFor(model => model.Capacity)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, "Hostel Description", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Description)
                                    @Html.ValidationMessageFor(model => model.Description)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Date_Entered, "Date Added", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Date_Entered)
                                    @Html.ValidationMessageFor(model => model.Date_Entered)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Activated, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Activated)
                                    @Html.ValidationMessageFor(model => model.Activated)
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Create" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        @Html.ActionLink("Back to List", "Index","", new{@class = "btn btn-success"})
                    </div>


                </div>
            </div>
        </div>
    </div>
    <div class="col-md-1"></div>
</div>


Abundance_Nk.Web/Areas/Admin/Views/Hostel/CreateHostelType.cshtml
@model Abundance_Nk.Web.Areas.Admin.ViewModels.HostelViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="col-md-1"></div>
    <div class="col-md-10">

        <div>
            @if (TempData["Message"] != null)
            {
                @Html.Partial("_Message", (Abundance_Nk.Model.Model.Message)TempData["Message"])
            }
        </div>

        <div class="panel panel-default">
            <div class="panel-heading panel-dark-head">
                <h4>Add Hostel</h4>
            </div>
            <div class="panel-body">
                <div class="col-md-12">

                    @using (Html.BeginForm("CreateHostelType", "Hostel", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                              
                            @Html.ValidationSummary(true)
                            

                            <div class="form-group">
                                @Html.LabelFor(model => model.HostelType.Hostel_Type_Name, "Hostel Type Name", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.HostelType.Hostel_Type_Name, new { @required = "required"})
                                    @Html.ValidationMessageFor(model => model.HostelType.Hostel_Type_Name)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.HostelType.Hostel_Type_Description, "Hostel Type Description", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.HostelType.Hostel_Type_Description)
                                    @Html.ValidationMessageFor(model => model.HostelType.Hostel_Type_Description)
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Create" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        @Html.ActionLink("Back to List", "ViewHostelTypes","", new{@class = "btn btn-success"})
                    </div>


                </div>
            </div>
        </div>
    </div>
    <div class="col-md-1"></div>
</div>


Abundance_Nk.Web/Areas/Admin/Views/Hostel/Delete.cshtml
@model Abundance_Nk.Model.Entity.HOSTEL

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="col-md-1"></div>
    <div class="col-md-10">

        <div>
            @if (TempData["Message"] != null)
            {
                @Html.Partial("_Message", (Abundance_Nk.Model.Model.Message)TempData["Message"])
            }
        </div>

        <div class="panel panel-default">
            <div class="panel-heading panel-dark-head">
                <h4>Are you sure you want to delete this?</h4>
            </div>
            <div class="panel-body">
                <div class="col-md-12">

                    <div>
                        <h5>HOSTEL</h5>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.Hostel_Name)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Hostel_Name)
                            </dd>
                            <br/>   

                            <dt>
                                @Html.DisplayNameFor(model => model.Capacity)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Capacity)
                            </dd>
                            <br />

                            <dt>
                                @Html.DisplayNameFor(model => model.Description)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Description)
                            </dd>
                            <br />

                            <dt>
                                @Html.DisplayNameFor(model => model.Date_Entered)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Date_Entered)
                            </dd>
                            <br />

                            <dt>
                                @Html.DisplayNameFor(model => model.Activated)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Activated)
                            </dd>
                            <br />

                            <dt>
                                @Html.DisplayName("Hostel Type")
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.HOSTEL_TYPE.Hostel_Type_Name)
                            </dd>

                        </dl>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Delete" class="btn btn-default" /> |
                                @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-success" })
                            </div>
                        }
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="col-md-1"></div>
</div>



Abundance_Nk.Web/Areas/Admin/Views/Hostel/DeleteHostelType.cshtml
@model Abundance_Nk.Web.Areas.Admin.ViewModels.HostelViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="col-md-1"></div>
    <div class="col-md-10">

        <div>
            @if (TempData["Message"] != null)
            {
                @Html.Partial("_Message", (Abundance_Nk.Model.Model.Message)TempData["Message"])
            }
        </div>

        <div class="panel panel-default">
            <div class="panel-heading panel-dark-head">
                <h4>Are you sure you want to delete this?</h4>
            </div>
            <div class="panel-body">
                <div class="col-md-12">

                    <div>
                        <h5>HOSTEL TYPE</h5>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayName("Hostel Type Name:")
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.HostelType.Hostel_Type_Name)
                            </dd>
                            <br/>   

                            <dt>
                                @Html.DisplayName("Description:")
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.HostelType.Hostel_Type_Description)
                            </dd> 
                             
                        </dl>

                        @using (Html.BeginForm("DeleteHostelType", "Hostel", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(model => model.HostelType.Hostel_Type_Id)

                            <div class="form-actions no-color">
                                <input type="submit" value="Delete" class="btn btn-default" /> |
                                @Html.ActionLink("Back to List", "ViewHostelTypes", "", new { @class = "btn btn-success" })
                            </div>
                        }
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="col-md-1"></div>
</div>



Abundance_Nk.Web/Areas/Admin/Views/Hostel/EditHostelType.cshtml
@model Abundance_Nk.Web.Areas.Admin.ViewModels.HostelViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="col-md-1"></div>
    <div class="col-md-10">

        <div>
            @if (TempData["Message"] != null)
            {
                @Html.Partial("_Message", (Abundance_Nk.Model.Model.Message)TempData["Message"])
            }
        </div>

        <div class="panel panel-default">
            <div class="panel-heading panel-dark-head">
                <h4>Edit Hostel Type</h4>
            </div>
            <div class="panel-body">
                <div class="col-md-12">
                    
                    @using (Html.BeginForm("EditHostelType", "Hostel", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h5>HOSTEL TYPE</h5>
                            <hr />
                            @Html.ValidationSummary(true)
                            @Html.HiddenFor(model => model.HostelType.Hostel_Type_Id)
                           
                            <div class="form-group">
                                @Html.LabelFor(model => model.HostelType.Hostel_Type_Name, "Hostel Type Name", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.HostelType.Hostel_Type_Name, new {@required = "required"})
                                    @Html.ValidationMessageFor(model => model.HostelType.Hostel_Type_Name)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.HostelType.Hostel_Type_Description, "Hostel Description", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.HostelType.Hostel_Type_Description)
                                    @Html.ValidationMessageFor(model => model.HostelType.Hostel_Type_Description)
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        @Html.ActionLink("Back to List", "ViewHostelTypes", "",new { @class = "btn btn-success" })
                    </div>
                      
                </div>
            </div>
        </div>
    </div> 
    <div class="col-md-1"></div>
</div>


                    