Abundance_Nk.Web/Areas/Admin/Controllers/ResultManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Abundance_Nk.Business;
using Abundance_Nk.Model.Model;
using Abundance_Nk.Web.Areas.Admin.ViewModels;
using Abundance_Nk.Web.Controllers;
using Abundance_Nk.Web.Models;
using IsolationLevel = System.Transactions.IsolationLevel;

namespace Abundance_Nk.Web.Areas.Admin.Controllers
{
    public class ResultManagerController : BaseController
    {
        private const string ID = "Id";
        private const string NAME = "Name";
        private StaffCourseAllocationViewModel viewModel;
        private string FileUploadURL = null;
        // GET: Admin/ResultManager
        public ActionResult Index()
        {
             try
            {
                StaffCourseAllocationViewModel viewModel = new StaffCourseAllocationViewModel();
                ViewBag.Session = viewModel.SessionSelectList;
                ViewBag.Semester = new SelectList(new List<Semester>(), ID, NAME);
                ViewBag.Programme = viewModel.ProgrammeSelectList;
                ViewBag.Department = new SelectList(new List<Department>(), ID, NAME);
                ViewBag.Level = new SelectList(viewModel.LevelList, ID, NAME);
                ViewBag.Course = new SelectList(new List<Course>(), ID, NAME);

            }
            catch (Exception ex)
            {
                SetMessage("Error Occured!" + ex.Message, Message.Category.Error);
            }
            return View();
        }
        [HttpPost]
        public ActionResult Index(StaffCourseAllocationViewModel viewModel)
        {
            try
            {
                if (viewModel != null)
                {
                    CourseAllocation courseAllocation = new CourseAllocation();
                    CourseAllocationLogic courseAllocationLogic = new CourseAllocationLogic();
                    courseAllocation = courseAllocationLogic.GetModelBy(p => p.Course_Id == viewModel.Course.Id && p.Department_Id == viewModel.Department.Id && p.Level_Id == viewModel.Level.Id && p.Programme_Id == viewModel.Programme.Id && p.Semester_Id == viewModel.Semester.Id && p.Session_Id == viewModel.Session.Id && p.USER.User_Name == User.Identity.Name);
                    if (courseAllocation == null)
                    {
                        if (!User.IsInRole("Admin"))
                        {
                            SetMessage("You are not allocated to this course, with this Programme-Department combination", Message.Category.Error);
                            KeepDropDownState(viewModel);
                            return RedirectToAction("Index");                            
                        }
                    }
                    GridView gv = new GridView();

                    DataTable ds = new DataTable();
                    List<ResultManageFormat> resultFormatList = new List<ResultManageFormat>();

                    SessionLogic sessionLogic = new SessionLogic();
                    Session session = sessionLogic.GetModelBy(p => p.Activated == true);
                    CourseRegistrationDetailLogic courseRegistrationDetailLogic = new CourseRegistrationDetailLogic();
                    List<CourseRegistrationDetail> courseRegistrationDetailList = new List<CourseRegistrationDetail>();
                    List<CourseRegistration> courseRegistrationList = new List<CourseRegistration>();
                    CourseRegistrationLogic courseRegistrationLogic = new CourseRegistrationLogic();
                    courseRegistrationList = courseRegistrationLogic.GetModelsBy(p => p.Session_Id == session.Id && p.Level_Id == viewModel.Level.Id && p.Department_Id == viewModel.Department.Id && p.Programme_Id == viewModel.Programme.Id);
                    if (viewModel.Course != null && viewModel.Semester != null && courseRegistrationList.Count > 0)
                    {
                        int count = 1;
                        foreach (CourseRegistration courseRegistration in courseRegistrationList)
                        {
                            courseRegistrationDetailList = courseRegistrationDetailLogic.GetModelsBy(p => p.Course_Id == viewModel.Course.Id && p.Semester_Id == viewModel.Semester.Id && p.Student_Course_Registration_Id == courseRegistration.Id);
                            if (courseRegistrationDetailList.Count > 0)
                            {

                                foreach (CourseRegistrationDetail courseRegistrationDetailItem in courseRegistrationDetailList)
                                {
                                    ResultManageFormat resultFormat = new ResultManageFormat();
                                    // resultFormat.SN = count;
                                    resultFormat.MATRICNO = courseRegistrationDetailItem.CourseRegistration.Student.MatricNumber;
                                    resultFormat.Course_Code = courseRegistrationDetailItem.Course.Code;
                                    resultFormat.Department = courseRegistrationDetailItem.Course.Department.Name;
                                    resultFormat.Level = courseRegistrationDetailItem.CourseRegistration.Level.Name;
                                    resultFormat.Programme = courseRegistrationDetailItem.CourseRegistration.Programme.Name;
                                    resultFormat.Semester = courseRegistrationDetailItem.Semester.Name;
                                    resultFormat.Session = courseRegistrationDetailItem.CourseRegistration.Session.Name;
                                    resultFormatList.Add(resultFormat);
                                    count++;
                                }
                            }
                        }
                    }

                    if (resultFormatList.Count > 0)
                    {
                        List<ResultManageFormat> list = resultFormatList.OrderBy(p => p.MATRICNO).ToList();
                        List<ResultManageFormat> sort = new List<ResultManageFormat>();
                        for (int i = 0; i < list.Count; i++)
                        {
                            list[i].SN = (i + 1);
                            sort.Add(list[i]);
                        }

                        gv.DataSource = sort;// resultFormatList.OrderBy(p => p.MATRICNO);
                        CourseLogic courseLogic = new CourseLogic();
                        Course course = courseLogic.GetModelBy(p => p.Course_Id == viewModel.Course.Id);
                        gv.Caption = course.Name.ToUpper() + " " +course.Code + " " + " DEPARTMENT OF " + " " + course.Department.Name.ToUpper() + " " + course.Unit + " " + "Units";
                        gv.DataBind();

                        string filename = course.Code.Replace("/", "").Replace("\\", "") + course.Department.Code + ".xls";
                        return new DownloadFileActionResult(gv, filename);
                    }
                    else
                    {
                        Response.Write("No data available for download");
                        Response.End();
                        return new JavaScriptResult();
                    }
                }
                else
                {
                    SetMessage("Input is null", Message.Category.Error);

                    KeepDropDownState(viewModel);

                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                SetMessage("Error occurred! " + ex.Message, Message.Category.Error);
            }


            return RedirectToAction("Index");
        }
        public void KeepDropDownState(StaffCourseAllocationViewModel viewModel)
        {
            try
            {
                ViewBag.Session = viewModel.SessionSelectList;
                ViewBag.Programme = viewModel.ProgrammeSelectList;
                ViewBag.Level = new SelectList(viewModel.LevelList, ID, NAME);
                ViewBag.User = viewModel.UserSelectList;
                if (viewModel.Semester != null)
                {
                    List<SessionSemester> sessionSemesterList = new List<SessionSemester>();
                    SessionSemesterLogic sessionSemesterLogic = new SessionSemesterLogic();
                    sessionSemesterList = sessionSemesterLogic.GetModelsBy(p => p.Session_Id == viewModel.Session.Id);

                    List<Semester> semesters = new List<Semester>();
                    foreach (SessionSemester sessionSemester in sessionSemesterList)
                    {
                        semesters.Add(sessionSemester.Semester);
                    }

                    ViewBag.Semester = new SelectList(semesters, ID, NAME, viewModel.Semester.Id);
                }
                if (viewModel.Department != null && viewModel.Department.Id > 0)
                {
                    DepartmentLogic departmentLogic = new DepartmentLogic();
                    List<Department> departments = new List<Department>();
                    departments = departmentLogic.GetBy(viewModel.Programme);

                    ViewBag.Department = new SelectList(departments, ID, NAME, viewModel.Department.Id);
                }
                if (viewModel.Course != null && viewModel.Course.Id > 0)
                {
                    List<Course> courseList = new List<Course>();
                    courseList = Utility.GetCoursesByLevelDepartmentAndSemester(viewModel.Level, viewModel.Department, viewModel.Semester);


Abundance_Nk.Web/Areas/Admin/Views/ResultManager/Index.cshtml
@model Abundance_Nk.Web.Areas.Admin.ViewModels.StaffCourseAllocationViewModel
@{
    ViewBag.Title = "DownloadResultSheet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if(TempData["Message"] != null)
{
    @Html.Partial("_Message",(Abundance_Nk.Model.Model.Message)TempData["Message"])
}

<script src="~/Scripts/jquery-1.11.1.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {

        function populateCourses() {
            $("#Course").empty();
            var values = new Array();
            //vals = [$("#Department").val(), $("#Level").val(), $("#Semester").val()];
            values[0] = $("#Department").val();
            values[1] = $("#Level").val();
            values[2] = $("#Semester").val();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetCourses", "StaffCourseAllocation")', // Calling json method
                traditional: true,
                data: { ids: values },
                // Get Selected Country ID.
                success: function (courses) {

                    $.each(courses, function (i, course) {
                        $("#Course").append('<option value="' + course.Value + '">' +
                             course.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve courses.' + ex);
                }
            });

        }
        //Programme Drop down Selected-change event
        $("#Programme").change(function () {
            if ($("#Department").val() > 0 && $("#Level").val() > 0 && $("#Semester").val() > 0) {
                populateCourses();
            }
            $("#Department").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetDepartments", "StaffCourseAllocation")', // Calling json method
                dataType: 'json',
                data: { id: $("#Programme").val() },
                // Get Selected Country ID.
                success: function (departments) {
                    $("#Department").append('<option value="' + 0 + '">' +
                            '-- Select Department --' + '</option>');
                    $.each(departments, function (i, department) {
                        $("#Department").append('<option value="' + department.Value + '">' +
                             department.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve departments.' + ex);
                }
            });
            return false;
        })
        //Session Drop down Selected change event
        $("#Session").change(function () {
            if ($("#Department").val() > 0 && $("#Level").val() > 0 && $("#Semester").val() > 0) {
                populateCourses();
            }

            $("#Semester").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetSemester", "StaffCourseAllocation")', // Calling json method
                dataType: 'json',
                data: { id: $("#Session").val() },
                // Get Selected Country ID.
                success: function (semesters) {
                    $("#Semester").append('<option value="' + 0 + '">' +
                           '-- Select Semester --' + '</option>');
                    $.each(semesters, function (i, semester) {
                        $("#Semester").append('<option value="' + semester.Value + '">' +
                             semester.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve semesters.' + ex);
                }
            });
            return false;
        })
        $("#Department").change(function () {
            if ($("#Department").val() > 0 && $("#Level").val() > 0 && $("#Semester").val() > 0) {
                populateCourses();
            }
        });
        $("#Session").change(function () {
            if ($("#Department").val() > 0 && $("#Level").val() > 0 && $("#Semester").val() > 0) {
                populateCourses();
            }
        });
        $("#Level").change(function () {
            if ($("#Department").val() > 0 && $("#Level").val() > 0 && $("#Semester").val() > 0) {
                populateCourses();
            }

        });




    });
</script>

@using(Html.BeginForm("Index","ResultManager",new { area = "Admin" },FormMethod.Post))
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-fw fa-download"></i>Download Result Sheet</h3>
        </div>
        <div class="panel-body">

            <div class="form-group">
                @Html.LabelFor(model => model.Session.Name,"Session",new { @class = "col-sm-2 control-label " })
                <div class="col-sm-10">
                    @Html.DropDownListFor(model => model.Session.Id,(IEnumerable<SelectListItem>)ViewBag.Session,new { @class = "form-control",@id = "Session",@required = "required" })
                    @Html.ValidationMessageFor(model => model.Session.Id,null,new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Semester.Name,"Semester",new { @class = "col-sm-2 control-label " })
                <div class="col-sm-10">
                    @Html.DropDownListFor(model => model.Semester.Id,(IEnumerable<SelectListItem>)ViewBag.Semester,new { @class = "form-control",@id = "Semester",@required = "required" })
                    @Html.ValidationMessageFor(model => model.Semester.Id,null,new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Programme.Name,"Programme",new { @class = "col-sm-2 control-label " })
                <div class="col-sm-10">
                    @Html.DropDownListFor(model => model.Programme.Id,(IEnumerable<SelectListItem>)ViewBag.Programme,new { @class = "form-control",@id = "Programme",@required = "required" })
                    @Html.ValidationMessageFor(model => model.Programme.Id,null,new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Department.Name,"Department",new { @class = "col-sm-2 control-label " })
                <div class="col-sm-10">
                    @Html.DropDownListFor(model => model.Department.Id,(IEnumerable<SelectListItem>)ViewBag.Department,new { @class = "form-control",@id = "Department",@required = "required" })
                    @Html.ValidationMessageFor(model => model.Department.Id,null,new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Level.Name,"Level",new { @class = "col-sm-2 control-label " })
                <div class="col-sm-10">
                    @Html.DropDownListFor(model => model.Level.Id,(IEnumerable<SelectListItem>)ViewBag.Level,new { @class = "form-control",@id = "Level",@required = "required" })
                    @Html.ValidationMessageFor(model => model.Level.Id,null,new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Course.Name,"Course",new { @class = "col-sm-2 control-label " })
                <div class="col-sm-10">
                    @Html.DropDownListFor(model => model.Course.Id,(IEnumerable<SelectListItem>)ViewBag.Course,new { @class = "form-control",@id = "Course",@required = "required" })
                    @Html.ValidationMessageFor(model => model.Course.Id,null,new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                    <input class="btn btn-success mr5 " type="submit" name="submit" id="submit" value="Download Here" />

                </div>
            </div>

        </div>
    </div>

}



Abundance_Nk.Web/Areas/Admin/Views/ResultManager/UploadCompositeSheeet.cshtml
@model Abundance_Nk.Web.Areas.Admin.ViewModels.StaffCourseAllocationViewModel
@{
    ViewBag.Title = "Upload Composite Sheet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (TempData["Message"] != null)
{
    @Html.Partial("_Message", (Abundance_Nk.Model.Model.Message)TempData["Message"])
}


<script src="~/Scripts/jquery-1.11.1.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {

        //Programme Drop down Selected-change event
        $("#Programme").change(function() {
            
            $("#Department").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetDepartments", "StaffCourseAllocation")', // Calling json method
                dataType: 'json',
                data: { id: $("#Programme").val() },
                // Get Selected Country ID.
                success: function(departments) {
                    $("#Department").append('<option value="' + 0 + '">' +
                        '-- Select Department --' + '</option>');
                    $.each(departments, function(i, department) {
                        $("#Department").append('<option value="' + department.Value + '">' +
                            department.Text + '</option>');
                    });
                },
                error: function(ex) {
                    alert('Failed to retrieve departments.' + ex);
                }
            });
            return false;
        });
        //Session Drop down Selected change event
        $("#Session").change(function() {
            
            $("#Semester").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetSemester", "StaffCourseAllocation")', // Calling json method
                dataType: 'json',
                data: { id: $("#Session").val() },
                // Get Selected Country ID.
                success: function(semesters) {
                    $("#Semester").append('<option value="' + 0 + '">' +
                        '-- Select Semester --' + '</option>');
                    $.each(semesters, function(i, semester) {
                        $("#Semester").append('<option value="' + semester.Value + '">' +
                            semester.Text + '</option>');
                    });
                },
                error: function(ex) {
                    alert('Failed to retrieve semesters.' + ex);
                }
            });
            return false;
        });
        //Department Drop down Selected-change event
        $("#Department").change(function () {

            $("#DepartmentOption").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetDepartmentOptions", "StudentCourseRegistration")', // Calling json method
                dataType: 'json',
                data: { progId: 3, DeptId: $("#Department").val() },

                success: function (departmentOptions) {

                    $("#Option").show();

                    $("#DepartmentOption").append('<option value="' + 0 + '">' +
                        '-- Select Department Option --' + '</option>');
                    $.each(departmentOptions, function (i, departmentOption) {
                        $("#DepartmentOption").append('<option value="' + departmentOption.Value + '">' +
                            departmentOption.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve department options.' + ex);
                }
            });
            return false;
        });
    });
    function Busy() {
        $("#busy").show();
    }
</script>

@using (Html.BeginForm("UploadCompositeSheeet", "ResultManager", new { area = "Admin" }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-fw fa-upload"></i>Upload Composite Sheet</h3>
        </div>
        <div class="panel-body">
            <div class="alert alert-warning alert-dismissable"><h4>Endeavor to Cross Check Fields and Verify Excel Data</h4></div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Session.Name, "Session", new { @class = "col-sm-2 control-label " })
                        <div class="col-sm-10">
                            @Html.DropDownListFor(model => model.Session.Id, (IEnumerable<SelectListItem>)ViewBag.Session, new { @class = "form-control", @id = "Session" })
                            @Html.ValidationMessageFor(model => model.Session.Id, null, new { @class = "text-danger" })
                        </div>

                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Semester.Name, "Semester", new { @class = "col-sm-2 control-label " })
                        <div class="col-sm-10">
                            @Html.DropDownListFor(model => model.Semester.Id, (IEnumerable<SelectListItem>)ViewBag.Semester, new { @class = "form-control", @id = "Semester" })
                            @Html.ValidationMessageFor(model => model.Semester.Id, null, new { @class = "text-danger" })
                        </div>

                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Programme.Name, "Programme", new { @class = "col-sm-2 control-label " })
                        <div class="col-sm-10">
                            @Html.DropDownListFor(model => model.Programme.Id, (IEnumerable<SelectListItem>)ViewBag.Programme, new { @class = "form-control", @id = "Programme" })
                            @Html.ValidationMessageFor(model => model.Programme.Id, null, new { @class = "text-danger" })
                        </div>

                    </div>
                </div>
                <div class="col-md-6">

                    <div class="form-group">
                        @Html.LabelFor(model => model.Department.Name, "Department", new { @class = "col-sm-2 control-label " })
                        <div class="col-sm-10">
                            @Html.DropDownListFor(model => model.Department.Id, (IEnumerable<SelectListItem>)ViewBag.Department, new { @class = "form-control", @id = "Department" })
                            @Html.ValidationMessageFor(model => model.Department.Id, null, new { @class = "text-danger" })
                        </div>

                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.DepartmentOption.Name, "DepartmentOption", new {@class = "col-sm-2 control-label "})
                        <div class="col-sm-10">
                            @Html.DropDownListFor(model => model.DepartmentOption.Id, (IEnumerable<SelectListItem>) ViewBag.DepartmentOption, new {@class = "form-control", @id = "DepartmentOption"})
                            @Html.ValidationMessageFor(model => model.DepartmentOption.Id, null, new {@class = "text-danger"})
                        </div>

                    </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Level.Name, "Level", new {@class = "col-sm-2 control-label "})
                            <div class="col-sm-10">
                                @Html.DropDownListFor(model => model.Level.Id, (IEnumerable<SelectListItem>) ViewBag.Level, new {@class = "form-control", @id = "Level"})
                                @Html.ValidationMessageFor(model => model.Level.Id, null, new {@class = "text-danger"})
                            </div>

                        </div>
                    </div>

                </div>

            <div class="row"> 
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.CourseMode.Name, "Course Mode", new { @class = "col-sm-2 control-label " })
                        <div class="col-sm-10">
                            @Html.DropDownListFor(model => model.CourseMode.Id, (IEnumerable<SelectListItem>)ViewBag.CourseMode, new { @class = "form-control", @required = "required" })
                            @Html.ValidationMessageFor(model => model.CourseMode.Id, null, new { @class = "text-danger" })
                        </div>

                    </div>
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(model => model.Level.Name, "Select File", new {@class = "col-sm-2 control-label "})
                    <div class="col-sm-10">
                        <input type="file" title="Upload Result" id="file" name="file" class="form-control"/>
                        <br/>
                    </div>

                </div>
            </div>

            <div class="row">
                
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-sm-2">

                        </div>
                        <div class="col-sm-10">
                            <input class="btn btn-success mr5 " type="submit" name="submit" id="submit" value="Upload File" onclick="Busy()"/>
                            <span id="busy" style="display:none">
                                <span>Processing...</span>
                                <img src="@Url.Content("~/Content/Images/bx_loader.gif")" />
                            </span>
                        </div>

                    </div>
                </div>


            </div>


            <br />
            @if (Model == null || Model.StudentResultFormatList == null)
            {
                return;
            }
            @if (Model != null && Model.StudentResultFormatList.Count > 0)
            {
                <table class="table table-responsive table-striped">
                    <tr>
                        <th>
                            S/N
                        </th>
                        <th>
                            NAME
                        </th>
                        <th>
                            MATRIC NUMBER
                        </th>
                        <th>
                            COURSES AND GRADES
                        </th>
                    </tr>
                    @for (int i = 0; i < Model.StudentResultFormatList.Count; i++)
                    {
                        <tr>
                            <td>
                                @{var sn = i + 1; } <span>@sn</span>
                            </td>
                            <td>
                                @Model.StudentResultFormatList[i].NAME
                            </td>
                            <td>
                                @Model.StudentResultFormatList[i].MATRICNO
                            </td>
                            <td>
                                @Model.StudentResultFormatList[i].Course_Code
                            </td>
                        </tr>
                    }
                </table>
                <br />
                <div class="form-group" style="text-align:center">

                    <div class="col-sm-10 pull-left">
                        @Html.ActionLink("Save", "SaveUploadedCompositeSheet", new { controller = "ResultManager", area = "Admin" }, new { @class = "btn btn-success mr5", @onclick = "Busy()" })
                        <span id="busy" style="display:none">
                            <span>Processing...</span>
                            <img src="@Url.Content("~/Content/Images/bx_loader.gif")" />
                        </span>
                    </div>
                </div>
            }
        </div>

    </div>

}
